library:
  upload:
    #base-path: /data/library/uploads  # Linux系统推荐路径
    base-path: D:/library/uploads   # Windows系统推荐路径
    book-path: ${library.upload.base-path}/books
    max-file-size: 200MB              # 修改最大文件大小